In [1]:
# AI Customer Churn Intelligence
#
# Objective:
# Generate AI-powered explanations and
# retention recommendations for customers
# identified as high churn risk.

In [2]:
import pandas as pd

df = pd.read_csv(
    "../data/processed/customer_risk_scoring_business.csv"
)

print(df.columns.tolist()[:10])

['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity']

In [3]:
high_risk = df[
    df["RiskLevel"] == "High"
]

high_risk.shape

(209, 24)

In [4]:
high_risk.head(5)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,ActualChurn,RiskScore,RiskLevel
1,2754-SDJRD,Female,1,No,No,8,Yes,Yes,Fiber optic,No,...,Yes,Month-to-month,Yes,Credit card (automatic),100.15,908.55,No,0,0.684193,High
5,4686-UXDML,Female,0,No,No,21,Yes,Yes,Fiber optic,No,...,Yes,Month-to-month,Yes,Credit card (automatic),99.85,1992.55,No,0,0.603512,High
13,4706-AXVKM,Female,1,No,No,11,Yes,Yes,Fiber optic,No,...,Yes,Month-to-month,Yes,Credit card (automatic),84.80,906.85,Yes,1,0.685949,High
17,1379-FRVEB,Male,0,No,Yes,15,Yes,Yes,Fiber optic,No,...,No,Month-to-month,Yes,Electronic check,91.00,1430.05,No,0,0.638422,High
20,7235-NXZCP,Male,1,No,No,2,Yes,Yes,Fiber optic,No,...,No,Month-to-month,Yes,Mailed check,74.85,156.4,Yes,1,0.725549,High

In [5]:
high_risk.iloc[0]

customerID                       2754-SDJRD
gender                               Female
SeniorCitizen                             1
Partner                                  No
Dependents                               No
tenure                                    8
PhoneService                            Yes
MultipleLines                           Yes
InternetService                 Fiber optic
OnlineSecurity                           No
OnlineBackup                             No
DeviceProtection                         No
TechSupport                             Yes
StreamingTV                             Yes
StreamingMovies                         Yes
Contract                     Month-to-month
PaperlessBilling                        Yes
PaymentMethod       Credit card (automatic)
MonthlyCharges                       100.15
TotalCharges                         908.55
Churn                                    No
ActualChurn                               0
RiskScore                          0.684193
RiskLevel                              High
Name: 1, dtype: object

In [6]:
# AI CHURN EXPLANATION ENGINE V1

def explain_customer(customer):
    
    reasons = []
    
    # Contract
    if customer["Contract"] == "Month-to-month":
        reasons.append(
            "Month-to-month contract"
        )
        
    # Tenure
    if customer["tenure"] < 12:
        reasons.append(
            "Short customer tenure"
        )
    
    # Internet
    if customer["InternetService"] == "Fiber optic":
        reasons.append(
            "Fiber optic internet service"
        )
     
     # Support
    if customer["TechSupport"] == "No":
        reasons.append(
            "No technical support service"
        )
    
    # Security
    if customer["OnlineSecurity"] == "No":
        reasons.append(
            "No online security service"
        )
    
    return reasons

In [7]:
# RETENTION RECOMMENDATION ENGINE

def generate_recommendations(customer):
    
    recommendations = []
    
    if customer["Contract"] == "Month-to-month":
        recommendations.append(
            "Offer discount for 1-year or 2-year contract"
        )
        
    if customer["OnlineSecurity"] == "No":
        recommendations.append(
            "Promote Online Security package"
        )

    if customer["TechSupport"] == "No":
        recommendations.append(
            "Offer Tech Support bundle"
        )

    if customer["tenure"] < 12:
        recommendations.append(
            "Launch onboarding retention campaign"
        )

    if customer["InternetService"] == "Fiber optic":
        recommendations.append(
            "Review customer satisfaction with Fiber Optic service"
        )

    return recommendations

In [8]:
customer = high_risk.iloc[0]

explain_customer(customer)

['Month-to-month contract',
 'Short customer tenure',
 'Fiber optic internet service',
 'No online security service']

In [9]:
# BUSINESS REPORT GENERATOR

def generate_report(customer):
    
    reasons = explain_customer(customer)
    
    recommendations = generate_recommendations(customer)
    
    report = f"""
CUSTOMER CHURN RISK REPORT

Customer ID: {customer["customerID"]}

Risk Score: {customer["RiskScore"]:.1%}
Risk Level: {customer["RiskLevel"]}

Main Risk Factors:
"""
    for reason in reasons:
        report += f"\n- {reason}"
    
    report += "\n\nRECOMMENDED ACTIONS:\n"
    
    for rec in recommendations:
        report += f"\n- {rec}"
    
    return report

In [10]:
generate_report(high_risk.iloc[0])

'\nCUSTOMER CHURN RISK REPORT\n\nCustomer ID: 2754-SDJRD\n\nRisk Score: 68.4%\nRisk Level: High\n\nMain Risk Factors:\n\n- Month-to-month contract\n- Short customer tenure\n- Fiber optic internet service\n- No online security service\n\nRECOMMENDED ACTIONS:\n\n- Offer discount for 1-year or 2-year contract\n- Promote Online Security package\n- Launch onboarding retention campaign\n- Review customer satisfaction with Fiber Optic service'

In [11]:
for i in range (3):
    print(generate_report(high_risk.iloc[i]))
    print("\n" + "="*80 + "\n")

CUSTOMER CHURN RISK REPORT

Customer ID: 2754-SDJRD

Risk Score: 68.4%
Risk Level: High

Main Risk Factors:

- Month-to-month contract
- Short customer tenure
- Fiber optic internet service
- No online security service

RECOMMENDED ACTIONS:

- Offer discount for 1-year or 2-year contract
- Promote Online Security package
- Launch onboarding retention campaign
- Review customer satisfaction with Fiber Optic service

================================================================================


CUSTOMER CHURN RISK REPORT

Customer ID: 4686-UXDML

Risk Score: 60.4%
Risk Level: High

Main Risk Factors:

- Month-to-month contract
- Fiber optic internet service
- No technical support service
- No online security service

RECOMMENDED ACTIONS:

- Offer discount for 1-year or 2-year contract
- Promote Online Security package
- Offer Tech Support bundle
- Review customer satisfaction with Fiber Optic service

================================================================================


CUSTOMER CHURN RISK REPORT

Customer ID: 4706-AXVKM

Risk Score: 68.6%
Risk Level: High

Main Risk Factors:

- Month-to-month contract
- Short customer tenure
- Fiber optic internet service
- No technical support service
- No online security service

RECOMMENDED ACTIONS:

- Offer discount for 1-year or 2-year contract
- Promote Online Security package
- Offer Tech Support bundle
- Launch onboarding retention campaign
- Review customer satisfaction with Fiber Optic service

================================================================================

In [12]:
# EXECUTIVE SUMMARY GENERATOR

def generate_executive_summary(customer):
    
    reasons = explain_customer(customer)
    
    summary = (
        f"Customer {customer["customerID"]} "
        f"has been classified as {customer["RiskLevel"]} Risk "
        f"with a predicted churn probability of "
        f"{customer["RiskScore"]:.1%}. "
    )
    
    if len(reasons) > 0:
        
        summary += (
            "The primary risk factors include "
            + ", ".join(reasons[:-1])
        )
        
        if len(reasons) > 1:
            summary += f" and {reasons[-1]}."
        
        else:
            summary += f"{reasons[0]}"
        
    summary += (
        " Based on historical customer behavior, "
        "similar profiles have shown an elevated "
        "probability of churn. "
        "A targeted retention strategy is recommended."
    )

    return summary

In [13]:
generate_executive_summary(
    high_risk.iloc[0]
)

'Customer 2754-SDJRD has been classified as High Risk with a predicted churn probability of 68.4%. The primary risk factors include Month-to-month contract, Short customer tenure, Fiber optic internet service and No online security service. Based on historical customer behavior, similar profiles have shown an elevated probability of churn. A targeted retention strategy is recommended.'

In [14]:
# Top 10 high risk customers

top_10 = high_risk.sort_values(
    by="RiskScore",
    ascending=False
). head(10)

top_10[[
    "customerID",
    "RiskScore",
    "RiskLevel"
]]

      customerID  RiskScore RiskLevel
1090  5178-LMXOP   0.855304      High
1221  0295-PPHDO   0.832206      High
1175  6861-XWTWQ   0.827888      High
1164  8884-ADFVN   0.823048      High
1109  1069-XAIEM   0.819436      High
627   9057-SIHCH   0.818499      High
647   6023-YEBUP   0.817763      High
1138  1400-MMYXY   0.817739      High
889   2545-EBUPK   0.817609      High
1355  6630-UJZMY   0.811898      High

In [15]:
for i in range(3):
    
    customer = top_10.iloc[i]
    
    print("=" * 80)
    
    print(
        generate_executive_summary(customer)
    )
    print("\n")

================================================================================
Customer 5178-LMXOP has been classified as High Risk with a predicted churn probability of 85.5%. The primary risk factors include Month-to-month contract, Short customer tenure, Fiber optic internet service, No technical support service and No online security service. Based on historical customer behavior, similar profiles have shown an elevated probability of churn. A targeted retention strategy is recommended.


================================================================================
Customer 0295-PPHDO has been classified as High Risk with a predicted churn probability of 83.2%. The primary risk factors include Month-to-month contract, Short customer tenure, Fiber optic internet service, No technical support service and No online security service. Based on historical customer behavior, similar profiles have shown an elevated probability of churn. A targeted retention strategy is recommended.


================================================================================
Customer 6861-XWTWQ has been classified as High Risk with a predicted churn probability of 82.8%. The primary risk factors include Month-to-month contract, Short customer tenure, Fiber optic internet service, No technical support service and No online security service. Based on historical customer behavior, similar profiles have shown an elevated probability of churn. A targeted retention strategy is recommended.

In [16]:
top_10["RiskScore"].describe()

count    10.000000
mean      0.824139
std       0.012381
min       0.811898
25%       0.817745
50%       0.818967
75%       0.826678
max       0.855304
Name: RiskScore, dtype: float64